Repository cyberbotics/webots_ros, pull requests merged in 2020-10, with the labels that each got.

#31 Feature fix dash usage
  launch/catch_the_bird.launch
  launch/complete_test.launch
  launch/e_puck_line.launch
  launch/keyboard_teleop.launch
  launch/panoramic_view_recorder.launch
  launch/pioneer3at.launch
  launch/robot_information_parser.launch
  launch/webots.launch
  launch/webots_ros_python.launch
  scripts/webots_launcher.py
Labels: bug

#34 Add Camera Exposure API
  src/complete_test.cpp
Labels: enhancement

#35 Feature recursive contact points
  CMakeLists.txt
  src/complete_test.cpp
  srv/node_get_contact_point_node.srv
  srv/node_get_number_of_contact_points.srv
Labels: enhancement

#36 Change coordinate system from NUE to ENU
  worlds/.catch_the_bird.wbproj
  worlds/.complete_test.wbproj
  worlds/.e-puck_line.wbproj
  worlds/.keyboard_teleop.wbproj
  worlds/.panoramic_view_recorder.wbproj
  worlds/.pioneer3at.wbproj
  worlds/.ros_python.wbproj
  worlds/catch_the_bird.wbt
  worlds/complete_test.wbt
  worlds/e-puck_line.wbt
  worlds/keyboard_teleop.wbt
  worlds/panoramic_view_recorder.wbt
  worlds/pioneer3at.wbt
  worlds/ros_python.wbt
Labels: bug, enhancement
